# Generated by Django 2.2.12 on 2021-03-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_image', models.FileField(upload_to='Advertisements/')),
            ],
        ),
    ]
