# Generated by Django 2.2.12 on 2021-03-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0043_auto_20210319_0454'),
        ('owner', '0004_visiblity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visiblity',
        ),
    ]
