# Generated by Django 2.2.12 on 2021-03-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0044_auto_20210319_0616'),
        ('owner', '0005_delete_visiblity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedShows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.Show')),
            ],
        ),
    ]
