# Generated by Django 2.2.12 on 2021-03-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_featuredshows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredshows',
            old_name='featured',
            new_name='show',
        ),
    ]
