# Generated by Django 2.2.12 on 2021-03-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0044_auto_20210319_0616'),
        ('owner', '0007_auto_20210324_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingShows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.Show')),
            ],
        ),
        migrations.CreateModel(
            name='TopPodcasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.CreatorDeatails')),
            ],
        ),
        migrations.CreateModel(
            name='PopularShows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.Show')),
            ],
        ),
    ]
