# Generated by Django 2.2.12 on 2021-04-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_auto_20210324_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='types',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
