# Generated by Django 3.1.7 on 2021-02-28 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0002_playlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayList',
            new_name='LikedSongs',
        ),
    ]
