# Generated by Django 3.1.7 on 2021-03-05 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0005_auto_20210302_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='usersprofile/'),
            preserve_default=False,
        ),
    ]
