# Generated by Django 2.2.12 on 2021-03-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0037_auto_20210317_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistcontent',
            name='types',
            field=models.CharField(blank=True, default='Playlist', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='playlistcontent',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.Playlist'),
        ),
    ]
