# Generated by Django 2.2.12 on 2021-03-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0038_auto_20210318_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistcontent',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.Playlist'),
        ),
        migrations.AlterField(
            model_name='playlistcontent',
            name='types',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
