# Generated by Django 3.1.7 on 2021-02-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatordeatails',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
