# Generated by Django 3.1.7 on 2021-03-01 10:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_creatordeatails_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='category',
        ),
        migrations.AlterField(
            model_name='contents',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contents',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contents',
            name='episode_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creatordeatails',
            name='about_me',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.category')),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='Show',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='creator.show'),
            preserve_default=False,
        ),
    ]
