# Generated by Django 3.1.7 on 2021-03-02 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_auto_20210301_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='thumbnail',
            field=models.FileField(default=django.utils.timezone.now, upload_to='showthumbnail/'),
            preserve_default=False,
        ),
    ]
