# Generated by Django 3.1.7 on 2021-03-05 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_show_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatordeatails',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='creatorprofile/'),
            preserve_default=False,
        ),
    ]
