# Generated by Django 3.1.7 on 2021-03-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
        ('creator', '0008_creatordeatails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
