# Generated by Django 3.1.7 on 2021-03-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0011_auto_20210308_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='followed_on',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='user',
            new_name='follower',
        ),
        migrations.AddField(
            model_name='follows',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
