# Generated by Django 3.1.7 on 2021-03-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0012_auto_20210308_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='total_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
