# Generated by Django 3.1.7 on 2021-03-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0014_auto_20210308_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='follows',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='follows',
            name='unfollows',
            field=models.FloatField(default=0, null=True),
        ),
    ]
