# Generated by Django 3.1.7 on 2021-03-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0015_auto_20210308_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follows',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='follows',
            name='unfollows',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
