# Generated by Django 2.2.12 on 2021-03-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0016_auto_20210308_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='description',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
