# Generated by Django 2.2.12 on 2021-03-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0017_auto_20210312_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='follower',
            new_name='creators',
        ),
    ]
