# Generated by Django 2.2.12 on 2021-03-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0020_auto_20210312_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='follows',
            name='unfollows',
        ),
        migrations.AlterField(
            model_name='follows',
            name='follow_type',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
