# Generated by Django 2.2.12 on 2021-03-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0022_remove_follows_total_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='episodes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.Contents'),
        ),
        migrations.AddField(
            model_name='follows',
            name='shows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.Show'),
        ),
    ]
