# Generated by Django 2.2.12 on 2021-03-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0024_auto_20210312_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='time_of_published',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='date_of_published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='time_of_published',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contents',
            name='date_of_published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
