# Generated by Django 2.2.12 on 2021-03-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0025_auto_20210312_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
