# Generated by Django 2.2.12 on 2021-03-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0026_show_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.Show'),
        ),
    ]
