# Generated by Django 2.2.12 on 2021-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0028_auto_20210313_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='follow_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='followshows',
            name='follow_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
