# Generated by Django 2.2.12 on 2021-03-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0029_auto_20210314_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
