# Generated by Django 2.2.12 on 2021-03-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0031_auto_20210315_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('listners', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contents',
            name='listeners',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Listeners',
        ),
        migrations.AddField(
            model_name='episodeanalytics',
            name='episodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Contents'),
        ),
    ]
