# Generated by Django 2.2.12 on 2021-03-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0034_contents_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='favorites',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
