# Generated by Django 2.2.12 on 2021-03-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0035_contents_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='favorites',
        ),
    ]
