# Generated by Django 2.2.12 on 2021-03-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0036_remove_contents_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiblity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
