# Generated by Django 2.2.12 on 2021-03-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0037_visiblity'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiblity',
            name='visiblity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
