# Generated by Django 2.2.12 on 2021-03-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0039_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
