# Generated by Django 2.2.12 on 2021-03-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0040_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visiblity',
        ),
    ]
