# Generated by Django 2.2.12 on 2021-03-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0045_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
