# Generated by Django 2.2.12 on 2021-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0050_showmoderators_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='roles',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
