# Generated by Django 2.2.12 on 2021-03-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0051_show_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='roles',
        ),
        migrations.DeleteModel(
            name='ShowModerators',
        ),
    ]
